services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./transport_helper:/transport_helper
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: >
      sh -c "python manage.py migrate
      && gunicorn transport_helper.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - database
  bot-app:
    build:
      context: .
    environment:
      - TOKEN=${TOKEN}
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: >
      sh -c "python bot_app/management/commands/main.py"
    depends_on:
      - web-app
  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
