# Generated by Django 4.0.3 on 2023-01-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedstation',
            name='station',
            field=models.CharField(max_length=255, verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='selectedstation',
            name='transport_number',
            field=models.CharField(max_length=255, verbose_name='number_of_transport'),
        ),
        migrations.AlterField(
            model_name='selectedstation',
            name='transport_type',
            field=models.CharField(max_length=255, verbose_name='name_of_transport'),
        ),
        migrations.AlterField(
            model_name='selectedtransport',
            name='transport_number',
            field=models.CharField(max_length=255, verbose_name='number_of_transport'),
        ),
        migrations.AlterField(
            model_name='selectedtransport',
            name='transport_type',
            field=models.CharField(max_length=255, verbose_name='name_of_transport'),
        ),
    ]
